apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-deployment
  namespace: container-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: briankopp/container-communication-bar:1.0.0
        ports:
        - containerPort: 3000
