apiVersion: v1
kind: Service
metadata:
  name: bar-service
  namespace: container-communication
  labels:
    service: bar
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: bar
  type: NodePort
